print("James Tan")
print("Villa Mendez, Mogpog, Marinduque")
print("December 20, 2002")
print("Marinduque State College")
print("BSIT")
print("2-B")
print("Gaming")
print("Watching")
print("Basketball")
print("Volleyball")
print("Table Tennis")